# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-31 06:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name=b'Information sent to players')),
                ('date_sent', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('week', models.PositiveSmallIntegerField(blank=0, db_index=True, default=0)),
                ('is_unread', models.BooleanField(default=True)),
                ('category', models.CharField(blank=True, max_length=80, null=True)),
                ('player', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='informs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
