# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-03 15:32
from __future__ import unicode_literals

from django.db import migrations
import world.msgs.models


class Migration(migrations.Migration):

    dependencies = [
        ("comms", "0010_auto_20161206_1912"),
        ("msgs", "0003_convert_header_to_tags"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[],
            options={
                "proxy": True,
            },
            bases=(world.msgs.models.MarkReadMixin, "comms.msg"),
        ),
        migrations.CreateModel(
            name="Journal",
            fields=[],
            options={
                "proxy": True,
            },
            bases=(world.msgs.models.MarkReadMixin, "comms.msg"),
        ),
        migrations.CreateModel(
            name="Messenger",
            fields=[],
            options={
                "proxy": True,
            },
            bases=(world.msgs.models.MarkReadMixin, "comms.msg"),
        ),
        migrations.CreateModel(
            name="Post",
            fields=[],
            options={
                "proxy": True,
            },
            bases=(world.msgs.models.MarkReadMixin, "comms.msg"),
        ),
        migrations.CreateModel(
            name="Rumor",
            fields=[],
            options={
                "proxy": True,
            },
            bases=(world.msgs.models.MarkReadMixin, "comms.msg"),
        ),
        migrations.CreateModel(
            name="Vision",
            fields=[],
            options={
                "proxy": True,
            },
            bases=(world.msgs.models.MarkReadMixin, "comms.msg"),
        ),
    ]
