# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 08:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("msgs", "0005_auto_20170920_0148"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inform",
            name="read_by",
        ),
    ]
