# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-07 18:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("msgs", "0007_inform_read_by"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Comment",
        ),
        migrations.DeleteModel(
            name="Vision",
        ),
    ]
