# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-25 01:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='category',
            field=models.CharField(blank=True, default=b'noble', max_length=255, null=True),
        ),
    ]
