# Generated by Django 2.2.16 on 2021-04-01 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dominion", "0002_fix_dominion_dependencies"),
        ("exploration", "0003_auto_20210401_0022"),
        ("petitions", "0006_auto_20210401_0022"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="craftingrecipe",
            name="known_by",
        ),
        migrations.RemoveField(
            model_name="craftingrecipe",
            name="primary_materials",
        ),
        migrations.RemoveField(
            model_name="craftingrecipe",
            name="secondary_materials",
        ),
        migrations.RemoveField(
            model_name="craftingrecipe",
            name="tertiary_materials",
        ),
        migrations.DeleteModel(
            name="CraftingMaterials",
        ),
        migrations.DeleteModel(
            name="CraftingMaterialType",
        ),
        migrations.DeleteModel(
            name="CraftingRecipe",
        ),
    ]
