# Generated by Django 2.2.24 on 2021-10-30 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0003_auto_20210704_1214"),
        ("dominion", "0003_auto_20210401_0026"),
    ]

    operations = [
        migrations.AddField(
            model_name="plotaction",
            name="org",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="actions",
                to="dominion.Organization",
            ),
        ),
        migrations.CreateModel(
            name="ActionPerEpisode",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "episode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="action_per_episodes",
                        to="character.Episode",
                    ),
                ),
                (
                    "player_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="action_per_episodes",
                        to="character.PlayerAccount",
                    ),
                ),
                (
                    "plot_action",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="action_per_episode",
                        to="dominion.PlotAction",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
