# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-19 03:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0004_auto_20161217_0654"),
        ("dominion", "0003_auto_20170118_0512"),
    ]

    operations = [
        migrations.AddField(
            model_name="crisis",
            name="required_clue",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="crises",
                to="character.Clue",
            ),
        ),
    ]
