# Generated by Django 2.2.24 on 2023-02-10 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0004_playeraccount_episodes"),
        ("dominion", "0005_auto_20211115_0144"),
    ]

    operations = [
        migrations.AddField(
            model_name="plotaction",
            name="episode",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="actions",
                to="character.Episode",
            ),
        ),
    ]
