# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-05-11 06:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dominion", "0009_auto_20170413_0308"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrgUnitModifiers",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unit_type",
                    models.PositiveSmallIntegerField(
                        blank=0,
                        choices=[
                            (0, b"Infantry"),
                            (1, b"Pike"),
                            (2, b"Cavalry"),
                            (3, b"Archers"),
                            (4, b"Longship"),
                            (5, b"Siege Weapon"),
                            (6, b"Galley"),
                            (7, b"Dromond"),
                        ],
                        default=0,
                    ),
                ),
                ("mod", models.SmallIntegerField(blank=0, default=0)),
                ("name", models.CharField(blank=True, max_length=80, null=True)),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unit_mods",
                        to="dominion.Organization",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Unit Modifiers",
            },
        ),
        migrations.RemoveField(
            model_name="army",
            name="commander",
        ),
        migrations.AddField(
            model_name="army",
            name="general",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="armies",
                to="dominion.PlayerOrNpc",
            ),
        ),
        migrations.AddField(
            model_name="army",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="armies",
                to="dominion.Army",
            ),
        ),
        migrations.AddField(
            model_name="army",
            name="temp_owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="loaned_armies",
                to="dominion.AssetOwner",
            ),
        ),
        migrations.AddField(
            model_name="militaryunit",
            name="origin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="units",
                to="dominion.Organization",
            ),
        ),
        migrations.AddField(
            model_name="orders",
            name="target_character",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="dominion.PlayerOrNpc",
            ),
        ),
        migrations.AlterField(
            model_name="agent",
            name="type",
            field=models.PositiveSmallIntegerField(
                blank=0,
                choices=[
                    (0, b"Guard"),
                    (1, b"Thug"),
                    (2, b"Spy"),
                    (3, b"Assistant"),
                    (4, b"Champion"),
                    (5, b"Animal"),
                    (6, b"Small Animal"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="militaryunit",
            name="commander",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="units",
                to="dominion.PlayerOrNpc",
            ),
        ),
        migrations.AlterField(
            model_name="militaryunit",
            name="unit_type",
            field=models.PositiveSmallIntegerField(
                blank=0,
                choices=[
                    (0, b"Infantry"),
                    (1, b"Pike"),
                    (2, b"Cavalry"),
                    (3, b"Archers"),
                    (4, b"Longship"),
                    (5, b"Siege Weapon"),
                    (6, b"Galley"),
                    (7, b"Dromond"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="orders",
            name="target_domain",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="dominion.Domain",
            ),
        ),
        migrations.AlterField(
            model_name="orders",
            name="target_land",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="dominion.Land",
            ),
        ),
        migrations.AlterField(
            model_name="orders",
            name="type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, b"Troop Training"),
                    (2, b"Explore territory"),
                    (3, b"Raid Domain"),
                    (4, b"Conquer Domain"),
                    (5, b"Enforce Order"),
                    (6, b"Besiege Castle"),
                    (7, b"March"),
                    (8, b"Defend"),
                    (9, b"Patrol"),
                    (10, b"Assist"),
                    (11, b"Bolster Morale"),
                    (12, b"Upgrade Equipment"),
                    (13, b"Crisis Response"),
                ],
                default=1,
            ),
        ),
    ]
