# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-19 03:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0015_auto_20170605_2252'),
        ('dominion', '0010_auto_20170511_0645'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='theories',
            field=models.ManyToManyField(blank=True, null=True, related_name='orgs', to='character.Theory'),
        ),
    ]
