# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-20 01:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dominion", "0011_organization_theories"),
    ]

    operations = [
        migrations.AddField(
            model_name="assetowner",
            name="min_materials_for_inform",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="assetowner",
            name="min_resources_for_inform",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="assetowner",
            name="min_silver_for_inform",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
