# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-11-06 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominion', '0013_auto_20171029_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionoocquestion',
            name='mark_answered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='crisisaction',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[
                (0, 'Draft'), (1, 'Needs Player Input'), (2, 'Needs GM Input'), (3, 'Cancelled'),
                (4, 'Pending Resolution'), (5, 'Resolved')], default=0),
        ),
    ]
