# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominion', '0014_auto_20171106_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crisisaction',
            name='assistants',
            field=models.ManyToManyField(blank=True, related_name='assisted_actions',
                                         through='dominion.CrisisActionAssistant', to='dominion.PlayerOrNpc'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='clues',
            field=models.ManyToManyField(blank=True, related_name='orgs', through='dominion.ClueForOrg',
                                         to='character.Clue'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='theories',
            field=models.ManyToManyField(blank=True, related_name='orgs', to='character.Theory'),
        ),
    ]
