# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-02 06:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dominion", "0020_auto_20180102_0655"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="domain",
            name="land",
        ),
        migrations.RemoveField(
            model_name="landmark",
            name="land",
        ),
        migrations.RemoveField(
            model_name="plotroom",
            name="land",
        ),
        migrations.RemoveField(
            model_name="shardhaven",
            name="land",
        ),
    ]
