# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-18 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominion', '0021_auto_20180102_0656'),
    ]

    operations = [
        migrations.AddField(
            model_name='crisisaction',
            name='free_action',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crisisactionassistant',
            name='free_action',
            field=models.BooleanField(default=False),
        ),
    ]
