# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-25 06:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dominion', '0022_auto_20180118_1856'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat', models.CharField(blank=True, max_length=80, null=True)),
                ('skill', models.CharField(blank=True, max_length=80, null=True)),
                ('resource', models.PositiveSmallIntegerField(choices=[(0, b'Economic'), (1, b'Military'), (2, b'Social')], default=0)),
                ('message', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_settings', to='dominion.Organization')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
