# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-23 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dominion", "0025_praiseorcondemn"),
    ]

    operations = [
        migrations.AddField(
            model_name="rpevent",
            name="risk",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, b"No Risk"),
                    (1, b"Minimal Risk"),
                    (2, b"Low Risk"),
                    (3, b"Reduced Risk"),
                    (4, b"Normal Risk"),
                    (5, b"Slightly Elevated Risk"),
                    (6, b"Moderately Elevated Risk"),
                    (7, b"Highly Elevated Risk"),
                    (8, b"Very High Risk"),
                    (9, b"Extreme Risk"),
                    (10, b"Suicidal Risk"),
                ],
                default=4,
            ),
        ),
    ]
