# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-04 15:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def populate_channels_and_boards(apps, schema_editor):
    from django.db.models import OuterRef, Subquery, F
    Organization = apps.get_model('dominion', 'Organization')
    ChannelDB = apps.get_model('comms', 'ChannelDB')
    ObjectDB = apps.get_model('objects', 'ObjectDB')
    chans = ChannelDB.objects.filter(db_lock_storage__icontains=OuterRef('name')).values_list('id')[:1]
    boards = ObjectDB.objects.filter(db_typeclass_path="typeclasses.bulletin_board.bboard.BBoard",
                                     db_lock_storage__icontains=OuterRef('name')).values_list('id')[:1]
    Organization.objects.filter(members__player__player__isnull=False).distinct().annotate(chan=Subquery(chans)).annotate(board=Subquery(boards)).update(org_board=F('board'), org_channel=F('chan'))


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0009_remove_objectdb_db_player'),
        ('comms', '0015_auto_20170706_2041'),
        ('dominion', '0029_auto_20180731_0001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fealty',
            options={'verbose_name_plural': 'Fealties'},
        ),
        migrations.AddField(
            model_name='member',
            name='has_seen_motd',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='org_board',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org', to='objects.ObjectDB'),
        ),
        migrations.AddField(
            model_name='organization',
            name='org_channel',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org', to='comms.ChannelDB'),
        ),
        migrations.RunPython(populate_channels_and_boards)
    ]
