# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-05 17:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("exploration", "0003_auto_20181105_1756"),
        ("dominion", "0032_auto_20180831_0557"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shardhaven",
            name="discovered_by",
        ),
        migrations.RemoveField(
            model_name="shardhaven",
            name="haven_type",
        ),
        migrations.RemoveField(
            model_name="shardhaven",
            name="location",
        ),
        migrations.RemoveField(
            model_name="shardhavenclue",
            name="clue",
        ),
        migrations.RemoveField(
            model_name="shardhavenclue",
            name="shardhaven",
        ),
        migrations.RemoveField(
            model_name="shardhavendiscovery",
            name="player",
        ),
        migrations.RemoveField(
            model_name="shardhavendiscovery",
            name="shardhaven",
        ),
        migrations.AlterField(
            model_name="plotroom",
            name="shardhaven_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tilesets",
                to="exploration.ShardhavenType",
            ),
        ),
    ]
