"""
This migration is about renaming Crisis to Plot, as well as all the related models.
"""
# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-28 00:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def convert_orgs_to_through_model(apps, schema_editor):
    """Convert the old implicit intermediary model to the new OrgPlotInvolvement model"""
    OrgPlotInvolvement = apps.get_model('dominion', 'OrgPlotInvolvement')
    OldThroughModel = apps.get_model('dominion', 'Plot_orgs')
    to_create_list = []
    for old in OldThroughModel.objects.all():
        to_create_list.append(OrgPlotInvolvement(plot=old.plot, org=old.organization))
    OrgPlotInvolvement.objects.bulk_create(to_create_list)


def convert_actions_for_events_into_beats(apps, schema_editor):
    """Convert actions m2m field into 'beat' foreignkey to update"""
    ActionEventThrough = apps.get_model('dominion', 'RPEvent_actions')
    for old in ActionEventThrough.objects.all():
        action = old.plotaction
        if action.update:
            event = old.rpevent
            event.beat = action.update
            event.save()


class Migration(migrations.Migration):

    dependencies = [
        ('dominion', '0034_auto_20181105_1756'),
    ]

    operations = [
        # rename the models
        migrations.RenameModel('Crisis', 'Plot'),
        migrations.RenameModel('CrisisAction', 'PlotAction'),
        migrations.RenameModel('CrisisUpdate', 'PlotUpdate'),
        migrations.RenameModel('CrisisActionAssistant', 'PlotActionAssistant'),
        migrations.CreateModel(
            name='OrgPlotInvolvement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_invite_members', models.BooleanField(default=False)),
                ('gm_notes', models.TextField(blank=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dominion.Organization',
                                          related_name='plot_involvement')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='orgplotinvolvement',
            name='plot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dominion.Plot',
                                    related_name='org_involvement'),
        ),
        migrations.CreateModel(
            name='PCPlotInvolvement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cast_status', models.PositiveSmallIntegerField(
                    choices=[(0, 'Required Cast'), (1, 'Main Cast'), (2, 'Supporting Cast'), (3, 'Extra'),
                             (4, 'Tangential')], default=1)),
                ('activity_status', models.PositiveSmallIntegerField(
                    choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Invited'), (3, 'Has RP Hook'), (4, 'Left'),
                             (5, 'Not Added')],
                    default=0)),
                ('admin_status', models.PositiveSmallIntegerField(
                    choices=[(4, 'Owner'), (3, 'GM'), (2, 'Recruiter'), (1, 'Player'), (0, 'Submitting Player')],
                    default=1)),
                ('recruiter_story', models.TextField(blank=True)),
                ('gm_notes', models.TextField(blank=True)),
                ('dompc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dominion.PlayerOrNpc',
                                            related_name="plot_involvement")),
                ('recruited_by', models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, blank=True, null=True,
                                                   to='dominion.PlayerOrNpc', related_name="plot_recruits")),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(model_name='plotaction', old_name='crisis', new_name='plot',),
        migrations.RenameField(model_name='plotactionassistant', old_name='crisis_action', new_name='plot_action',),
        migrations.RenameField(model_name='plot', old_name='parent_crisis',new_name='parent_plot'),
        migrations.RenameField(model_name='plotupdate', old_name='crisis', new_name='plot'),
        migrations.AddField(
            model_name='plot',
            name='usage',
            field=models.SmallIntegerField(choices=[(0, 'Crisis'), (1, 'GM Plot'), (2, 'Player-Run Plot'),
                                                    (3, 'Pitch')],
                                           default=0),
        ),
        migrations.AddField(
            model_name='plot',
            name='temp_orgs',
            field=models.ManyToManyField(blank=True, related_name='plots', through='dominion.OrgPlotInvolvement',
                                         through_fields=("plot", "dompc"),
                                         to='dominion.Organization'),
        ),
        migrations.RunPython(convert_orgs_to_through_model),
        migrations.RemoveField(model_name="plot", name="orgs"),
        migrations.RenameField(model_name="plot", old_name="temp_orgs", new_name="orgs"),
        migrations.AlterField(
            model_name='plotupdate',
            name='episode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='plot_updates', to='character.Episode'),
        ),
        migrations.AlterUniqueTogether(
            name='plotactionassistant',
            unique_together=set([('plot_action', 'dompc')]),
        ),
        migrations.AddField(
            model_name='pcplotinvolvement',
            name='plot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dominion.Plot',
                                    related_name='dompc_involvement'),
        ),
        migrations.AddField(
            model_name='plot',
            name='dompcs',
            field=models.ManyToManyField(blank=True, related_name='plots', through='dominion.PCPlotInvolvement',
                                         to='dominion.PlayerOrNpc'),
        ),
        migrations.AlterField(
            model_name='plot',
            name='parent_plot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='subplots', to='dominion.Plot'),
        ),
        migrations.AddField(
            model_name='plot',
            name='search_tags',
            field=models.ManyToManyField(blank=True, related_name='plots', to='character.SearchTag'),
        ),
        migrations.AddField(
            model_name='plotaction',
            name='search_tags',
            field=models.ManyToManyField(blank=True, related_name='actions', to='character.SearchTag'),
        ),
        migrations.AddField(
            model_name='plotupdate',
            name='search_tags',
            field=models.ManyToManyField(blank=True, related_name='plot_updates', to='character.SearchTag'),
        ),
        migrations.AddField(
            model_name='rpevent',
            name='search_tags',
            field=models.ManyToManyField(blank=True, related_name='events', to='character.SearchTag'),
        ),
        migrations.AddField(
            model_name='rpevent',
            name='beat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='events', to='dominion.PlotUpdate'),
        ),
        migrations.RunPython(convert_actions_for_events_into_beats),
        migrations.RemoveField(model_name='rpevent', name='actions'),
        migrations.AlterField(
            model_name='plotaction',
            name='update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='actions', to='dominion.PlotUpdate'),
        ),
        migrations.RenameField(model_name='plotaction', old_name='update', new_name='beat'),
        migrations.AlterModelOptions(
            name='plot',
            options={'verbose_name_plural': 'Plots'},
        ),
    ]
