# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-07 12:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dominion", "0036_plotaction_working"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plotaction",
            name="plot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="actions",
                to="dominion.Plot",
            ),
        ),
    ]
