# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-12 21:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def create_categories(apps, schema_editor):
    PrestigeCategory = apps.get_model('dominion', 'PrestigeCategory')
    categories = [
        PrestigeCategory(name='Fashion', male_noun='fashion icon', female_noun='fashion icon'),
        PrestigeCategory(name='Design', male_noun='designer', female_noun='designer'),
        PrestigeCategory(name='Event', male_noun='host', female_noun='hostess'),
        PrestigeCategory(name='Champion', male_noun='Champion', female_noun='Champion'),
        PrestigeCategory(name='Athletics', male_noun='athlete', female_noun='athlete'),
        PrestigeCategory(name='Military', male_noun='soldier', female_noun='soldier'),
        PrestigeCategory(name='Investment', male_noun='investor', female_noun='investor'),
        PrestigeCategory(name='Charity', male_noun='philanthropist', female_noun='philanthropist'),
    ]
    PrestigeCategory.objects.bulk_create(categories)


class Migration(migrations.Migration):

    dependencies = [
        ('dominion', '0037_auto_20181207_1202'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrestigeAdjustment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.PositiveSmallIntegerField(choices=[(0, b'Fame'), (1, b'Legend')], default=0)),
                ('adjusted_on', models.DateTimeField(auto_now_add=True)),
                ('adjusted_by', models.PositiveIntegerField(default=0)),
                ('reason', models.TextField(blank=True, null=True)),
                ('asset_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestige_adjustments', to='dominion.AssetOwner')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PrestigeCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('male_noun', models.CharField(max_length=30)),
                ('female_noun', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(create_categories),
        migrations.AddField(
            model_name='prestigeadjustment',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dominion.PrestigeCategory'),
        ),
    ]
