# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-16 16:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dominion', '0040_auto_20181216_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrestigeNomination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pending', models.BooleanField(default=True)),
                ('adjust_type', models.PositiveSmallIntegerField(choices=[(0, b'Fame'), (1, b'Legend')], default=0)),
                ('adjust_size', models.PositiveSmallIntegerField(choices=[(0, b'Small'), (1, b'Medium'), (2, b'Large'), (3, b'Huge')], default=0)),
                ('reason', models.CharField(blank=True, max_length=40, null=True)),
                ('long_reason', models.TextField()),
                ('approved_by', models.ManyToManyField(related_name='_prestigenomination_approved_by_+', to='dominion.PlayerOrNpc')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dominion.PrestigeCategory')),
                ('nominator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dominion.PlayerOrNpc')),
                ('nominees', models.ManyToManyField(related_name='_prestigenomination_nominees_+', to='dominion.AssetOwner')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
