# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-30 16:27
from __future__ import unicode_literals

from django.db import migrations, models


def fix_notes(apps, schema_editor):
    Member = apps.get_model("dominion", "Member")
    Member.objects.filter(desc="True").update(desc="")
    Member.objects.filter(public_notes="True").update(public_notes="")
    Member.objects.filter(officer_notes="True").update(officer_notes="")


class Migration(migrations.Migration):

    dependencies = [
        ('dominion', '0042_auto_20181216_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='desc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='officer_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='public_notes',
            field=models.TextField(blank=True),
        ),
        migrations.RunPython(fix_notes),
    ]
