# Generated by Django 2.2.9 on 2019-12-28 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dominion", "0045_auto_20190415_2022"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accounttransaction",
            name="do_weekly",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name="agent",
            name="type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Guard"),
                    (1, "Thug"),
                    (2, "Spy"),
                    (3, "Assistant"),
                    (4, "Champion"),
                    (5, "Animal"),
                    (6, "Small Animal"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="agentmission",
            name="active",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name="craftingrecipe",
            name="allow_adorn",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name="craftingrecipe",
            name="lock_storage",
            field=models.TextField(
                blank=True, help_text="defined in setup_utils", verbose_name="locks"
            ),
        ),
        migrations.AlterField(
            model_name="domainproject",
            name="type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Build Housing"),
                    (2, "Build Farms"),
                    (3, "Build Mines"),
                    (4, "Build Mills"),
                    (5, "Build Defenses"),
                    (6, "Build Siege Weapons"),
                    (7, "Muster Troops"),
                    (9, "Build Troop Equipment"),
                ],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="land",
            name="landlocked",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name="land",
            name="terrain",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Coast"),
                    (2, "Desert"),
                    (3, "Grassland"),
                    (4, "Hill"),
                    (5, "Mountain"),
                    (6, "Ocean"),
                    (7, "Plains"),
                    (8, "Snow"),
                    (9, "Tundra"),
                    (10, "Forest"),
                    (11, "Jungle"),
                    (12, "Marsh"),
                    (13, "Archipelago"),
                    (14, "Flood Plains"),
                    (15, "Ice"),
                    (16, "Lakes"),
                    (17, "Oasis"),
                ],
                default=7,
            ),
        ),
        migrations.AlterField(
            model_name="landmark",
            name="landmark_type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Unknown"),
                    (1, "Faith"),
                    (2, "Cultural"),
                    (3, "Historical"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="pc_exists",
            field=models.BooleanField(
                blank=True,
                default=True,
                help_text="Whether this member is a player character in the database",
            ),
        ),
        migrations.AlterField(
            model_name="militaryunit",
            name="unit_type",
            field=models.PositiveSmallIntegerField(
                blank=0,
                choices=[
                    (0, "Infantry"),
                    (1, "Pike"),
                    (2, "Cavalry"),
                    (3, "Archers"),
                    (4, "Longship"),
                    (5, "Siege Weapon"),
                    (6, "Galley"),
                    (8, "Cog"),
                    (7, "Dromond"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="minister",
            name="category",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Population"),
                    (1, "Income"),
                    (2, "Farming"),
                    (3, "Productivity"),
                    (4, "Upkeep"),
                    (5, "Loyalty"),
                    (6, "Warfare"),
                ],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="orders",
            name="type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Troop Training"),
                    (2, "Explore territory"),
                    (3, "Raid Domain"),
                    (4, "Conquer Domain"),
                    (5, "Enforce Order"),
                    (6, "Besiege Castle"),
                    (7, "March"),
                    (8, "Defend"),
                    (9, "Patrol"),
                    (10, "Assist"),
                    (11, "Bolster Morale"),
                    (12, "Upgrade Equipment"),
                    (13, "Crisis Response"),
                ],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="category",
            field=models.CharField(
                blank=True, default="noble", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="fealty",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orgs",
                to="dominion.Fealty",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="lock_storage",
            field=models.TextField(
                blank=True, help_text="defined in setup_utils", verbose_name="locks"
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="rank_10_female",
            field=models.CharField(
                blank=True, default="Serf", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="rank_10_male",
            field=models.CharField(
                blank=True, default="Serf", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="rank_1_female",
            field=models.CharField(
                blank=True, default="Princess", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="rank_1_male",
            field=models.CharField(
                blank=True, default="Prince", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="rank_2_female",
            field=models.CharField(
                blank=True, default="Voice", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="rank_2_male",
            field=models.CharField(
                blank=True, default="Voice", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="rank_3_female",
            field=models.CharField(
                blank=True, default="Noble Family", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="rank_3_male",
            field=models.CharField(
                blank=True, default="Noble Family", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="rank_4_female",
            field=models.CharField(
                blank=True, default="Trusted House Servants", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="rank_4_male",
            field=models.CharField(
                blank=True, default="Trusted House Servants", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="rank_5_female",
            field=models.CharField(
                blank=True, default="Noble Vassals", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="rank_5_male",
            field=models.CharField(
                blank=True, default="Noble Vassals", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="rank_6_female",
            field=models.CharField(
                blank=True, default="Vassals of Esteem", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="rank_6_male",
            field=models.CharField(
                blank=True, default="Vassals of Esteem", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="rank_7_female",
            field=models.CharField(
                blank=True, default="Known Commoners", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="rank_7_male",
            field=models.CharField(
                blank=True, default="Known Commoners", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="rank_8_female",
            field=models.CharField(
                blank=True, default="Sworn Commoners", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="rank_8_male",
            field=models.CharField(
                blank=True, default="Sworn Commoners", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="rank_9_female",
            field=models.CharField(
                blank=True, default="Forgotten Commoners", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="rank_9_male",
            field=models.CharField(
                blank=True, default="Forgotten Commoners", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="orgeventparticipation",
            name="social",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Social Resources spent by the Org Sponsor"
            ),
        ),
        migrations.AlterField(
            model_name="orgrelationship",
            name="history",
            field=models.TextField(
                blank=True, verbose_name="History of these organizations"
            ),
        ),
        migrations.AlterField(
            model_name="orgrelationship",
            name="name",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=255,
                verbose_name="Name of the relationship",
            ),
        ),
        migrations.AlterField(
            model_name="orgunitmodifiers",
            name="unit_type",
            field=models.PositiveSmallIntegerField(
                blank=0,
                choices=[
                    (0, "Infantry"),
                    (1, "Pike"),
                    (2, "Cavalry"),
                    (3, "Archers"),
                    (4, "Longship"),
                    (5, "Siege Weapon"),
                    (6, "Galley"),
                    (8, "Cog"),
                    (7, "Dromond"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="pceventparticipation",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "Main Host"), (1, "Host"), (2, "Guest")], default=2
            ),
        ),
        migrations.AlterField(
            model_name="playerornpc",
            name="alive",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name="plot",
            name="headline",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="News-style bulletin",
            ),
        ),
        migrations.AlterField(
            model_name="plot",
            name="public",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name="plotaction",
            name="action_points",
            field=models.PositiveSmallIntegerField(
                blank=0,
                default=0,
                help_text="How many action points spent by player/assistants.",
            ),
        ),
        migrations.AlterField(
            model_name="plotaction",
            name="actions",
            field=models.TextField(
                blank=True,
                help_text="The writeup the player submits of their actions, used for GMing.",
            ),
        ),
        migrations.AlterField(
            model_name="plotaction",
            name="category",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Unknown"),
                    (1, "Combat"),
                    (2, "Support"),
                    (3, "Sabotage"),
                    (4, "Diplomacy"),
                    (5, "Scouting"),
                    (6, "Research"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="plotaction",
            name="gemit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="actions",
                to="character.StoryEmit",
            ),
        ),
        migrations.AlterField(
            model_name="plotaction",
            name="gm_notes",
            field=models.TextField(
                blank=True, verbose_name="Any ooc notes for other GMs"
            ),
        ),
        migrations.AlterField(
            model_name="plotaction",
            name="prefer_offscreen",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="plotaction",
            name="public",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="plotaction",
            name="roll",
            field=models.SmallIntegerField(
                blank=True, default=-9999, help_text="Current dice roll"
            ),
        ),
        migrations.AlterField(
            model_name="plotaction",
            name="secret_story",
            field=models.TextField(
                blank=True, verbose_name="Any secret story written for the player"
            ),
        ),
        migrations.AlterField(
            model_name="plotaction",
            name="skill_used",
            field=models.CharField(
                blank=True,
                default="investigation",
                help_text="The skill the player chose to use",
                max_length=80,
            ),
        ),
        migrations.AlterField(
            model_name="plotaction",
            name="stat_used",
            field=models.CharField(
                blank=True,
                default="perception",
                help_text="The stat the player chose to use",
                max_length=80,
            ),
        ),
        migrations.AlterField(
            model_name="plotaction",
            name="story",
            field=models.TextField(
                blank=True, verbose_name="Story written by the GM for the player"
            ),
        ),
        migrations.AlterField(
            model_name="plotaction",
            name="topic",
            field=models.CharField(
                blank=True, help_text="Keywords or tldr or title", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="plotaction",
            name="working",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="action",
                to="magic.Working",
            ),
        ),
        migrations.AlterField(
            model_name="plotactionassistant",
            name="action_points",
            field=models.PositiveSmallIntegerField(
                blank=0,
                default=0,
                help_text="How many action points spent by player/assistants.",
            ),
        ),
        migrations.AlterField(
            model_name="plotactionassistant",
            name="actions",
            field=models.TextField(
                blank=True,
                help_text="The writeup the player submits of their actions, used for GMing.",
            ),
        ),
        migrations.AlterField(
            model_name="plotactionassistant",
            name="economic",
            field=models.PositiveSmallIntegerField(
                blank=0,
                default=0,
                help_text="Additional economic resources added by the player",
            ),
        ),
        migrations.AlterField(
            model_name="plotactionassistant",
            name="military",
            field=models.PositiveSmallIntegerField(
                blank=0,
                default=0,
                help_text="Additional military resources added by the player",
            ),
        ),
        migrations.AlterField(
            model_name="plotactionassistant",
            name="roll",
            field=models.SmallIntegerField(
                blank=True, default=-9999, help_text="Current dice roll"
            ),
        ),
        migrations.AlterField(
            model_name="plotactionassistant",
            name="secret_actions",
            field=models.TextField(
                blank=True, verbose_name="Secret actions the player is taking"
            ),
        ),
        migrations.AlterField(
            model_name="plotactionassistant",
            name="silver",
            field=models.PositiveSmallIntegerField(
                blank=0, default=0, help_text="Additional silver added by the player"
            ),
        ),
        migrations.AlterField(
            model_name="plotactionassistant",
            name="skill_used",
            field=models.CharField(
                blank=True,
                default="investigation",
                help_text="The skill the player chose to use",
                max_length=80,
            ),
        ),
        migrations.AlterField(
            model_name="plotactionassistant",
            name="social",
            field=models.PositiveSmallIntegerField(
                blank=0,
                default=0,
                help_text="Additional social resources added by the player",
            ),
        ),
        migrations.AlterField(
            model_name="plotactionassistant",
            name="stat_used",
            field=models.CharField(
                blank=True,
                default="perception",
                help_text="The stat the player chose to use",
                max_length=80,
            ),
        ),
        migrations.AlterField(
            model_name="plotactionassistant",
            name="topic",
            field=models.CharField(
                blank=True, help_text="Keywords or tldr or title", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="plotupdate",
            name="desc",
            field=models.TextField(
                blank=True, verbose_name="Story of what happened this update"
            ),
        ),
        migrations.AlterField(
            model_name="plotupdate",
            name="gm_notes",
            field=models.TextField(blank=True, verbose_name="Staff-visible notes"),
        ),
        migrations.AlterField(
            model_name="plotupdate",
            name="ooc_notes",
            field=models.TextField(blank=True, verbose_name="Player-visible ooc notes"),
        ),
        migrations.AlterField(
            model_name="praiseorcondemn",
            name="number_used",
            field=models.PositiveSmallIntegerField(
                default=1, help_text="Number of praises/condemns used from weekly pool"
            ),
        ),
        migrations.AlterField(
            model_name="prestigeadjustment",
            name="adjusted_by",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="prestigeadjustment",
            name="adjustment_type",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "Fame"), (1, "Legend")], default=0
            ),
        ),
        migrations.AlterField(
            model_name="prestigenomination",
            name="adjust_size",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "Small"), (1, "Medium"), (2, "Large"), (3, "Huge")],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="prestigenomination",
            name="adjust_type",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "Fame"), (1, "Legend")], default=0
            ),
        ),
        migrations.AlterField(
            model_name="reputation",
            name="favor",
            field=models.IntegerField(
                default=0,
                help_text="A percentage of the org's prestige applied to player's propriety.",
            ),
        ),
        migrations.AlterField(
            model_name="rpevent",
            name="celebration_tier",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (0, "Small"),
                    (1, "Average"),
                    (2, "Refined"),
                    (3, "Grand"),
                    (4, "Extravagant"),
                    (5, "Legendary"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="rpevent",
            name="plotroom",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events_held_here",
                to="dominion.PlotRoom",
            ),
        ),
        migrations.AlterField(
            model_name="rpevent",
            name="risk",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (0, "No Risk"),
                    (1, "Minimal Risk"),
                    (2, "Low Risk"),
                    (3, "Reduced Risk"),
                    (4, "Normal Risk"),
                    (5, "Slightly Elevated Risk"),
                    (6, "Moderately Elevated Risk"),
                    (7, "Highly Elevated Risk"),
                    (8, "Very High Risk"),
                    (9, "Extreme Risk"),
                    (10, "Suicidal Risk"),
                ],
                default=4,
            ),
        ),
    ]
