# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-28 15:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exploration', '0054_auto_20190728_1520'),
        ('petitions', '0004_auto_20190728_1520'),
        ('dominion', '0045_auto_20190415_2022'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CraftingMaterials',
        ),
        migrations.DeleteModel(
            name='CraftingMaterialType',
        ),
        migrations.DeleteModel(
            name='CraftingRecipe',
        ),
    ]
