# Generated by Django 2.2.12 on 2020-07-19 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dominion', '0047_actionrequirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='story_coordinator',
            field=models.BooleanField(default=False, verbose_name="Whether they're a coordinator for this org"),
        ),
        migrations.AddField(
            model_name='orgplotinvolvement',
            name='rank_requirement',
            field=models.PositiveSmallIntegerField(blank=True, default=10),
        ),
        migrations.AlterField(
            model_name='actionrequirement',
            name='clue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='character.Clue'),
        ),
        migrations.AlterField(
            model_name='actionrequirement',
            name='fulfilled_by',
            field=models.ForeignKey(blank=True, help_text='For non-amount clues, who satisfied the requirement', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requirements_fulfilled', to='dominion.PlayerOrNpc'),
        ),
        migrations.AlterField(
            model_name='actionrequirement',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='objects.ObjectDB'),
        ),
        migrations.AlterField(
            model_name='actionrequirement',
            name='revelation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='character.Revelation'),
        ),
        migrations.AlterField(
            model_name='actionrequirement',
            name='rfr',
            field=models.ForeignKey(blank=True, help_text='PlotUpdate that player specified to fill this requirement', null=True, on_delete=django.db.models.deletion.PROTECT, to='dominion.PlotUpdate'),
        ),
        migrations.AlterField(
            model_name='actionrequirement',
            name='skill_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='magic.SkillNode'),
        ),
        migrations.AlterField(
            model_name='actionrequirement',
            name='spell',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='magic.Spell'),
        ),
    ]
