# Generated by Django 2.2.10 on 2020-10-31 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("objects", "0011_auto_20191025_0831"),
        ("dominion", "0001_squashed_dominion"),
        ("character", "0001_squashed_character"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvocableEntity",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, unique=True)),
                ("public", models.BooleanField(default=True)),
                (
                    "character",
                    models.ForeignKey(
                        blank=True,
                        help_text="An in-game character object for this deity/being that can be invoked/worshipped",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="objects.ObjectDB",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Invocable Entities",
            },
        ),
        migrations.CreateModel(
            name="Prayer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Body of the prayer")),
                ("db_date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prayers",
                        to="objects.ObjectDB",
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prayers",
                        to="prayer.InvocableEntity",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PrayerAnswer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sign", models.TextField(blank=True)),
                ("gm_notes", models.TextField(blank=True)),
                ("db_date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "manifestation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="dominion.RPEvent",
                    ),
                ),
                (
                    "miracle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="character.Episode",
                    ),
                ),
                (
                    "prayer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="answer",
                        to="prayer.Prayer",
                    ),
                ),
                (
                    "vision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="character.Clue",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EntityAlias",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("alias", models.CharField(max_length=80, unique=True)),
                (
                    "entity",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliases",
                        to="prayer.InvocableEntity",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Entity Aliases",
            },
        ),
    ]
