# Generated by Django 2.2.24 on 2022-07-15 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prayer", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Religion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, db_index=True, max_length=25, null=True, unique=True
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
