# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-28 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weather", "0002_auto_20181027_1823"),
    ]

    operations = [
        migrations.AddField(
            model_name="weathertype",
            name="automated",
            field=models.BooleanField(default=True, verbose_name=b"Automated"),
        ),
    ]
