# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-01 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_weathertype_automated'),
    ]

    operations = [
        migrations.AddField(
            model_name='weathertype',
            name='multiplier',
            field=models.IntegerField(default=1, help_text=b'Multiply weather emit weights by this value when picking a weather; higher values make the weather more likely.', verbose_name=b'Weight Multiplier'),
        ),
        migrations.AlterField(
            model_name='weathertype',
            name='automated',
            field=models.BooleanField(default=True, help_text=b'Should this weather ever occur automatically?', verbose_name=b'Automated'),
        ),
    ]
