# Generated by Django 2.2.16 on 2020-11-29 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("traits", "0002_auto_20201108_1757"),
        ("conditions", "0002_auto_20190503_1914"),
    ]

    operations = [
        migrations.CreateModel(
            name="Wound",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "severity",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "serious wound"), (1, "permanent wound")],
                        default=0,
                    ),
                ),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wounds",
                        to="objects.ObjectDB",
                    ),
                ),
                (
                    "trait",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wounds",
                        to="traits.Trait",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
