# Generated by Django 2.2.16 on 2021-03-12 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conditions", "0004_characterhealthstatus"),
    ]

    operations = [
        migrations.AddField(
            model_name="wound",
            name="healing",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
