# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-28 15:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crafting', '0001_initial'),
        ('petitions', '0003_brokeredsale_broker_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brokeredsale',
            name='crafting_material_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crafting.CraftingMaterialType'),
        ),
    ]
