# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-08 09:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("petitions", "0004_auto_20190723_1746"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="petition",
            options={"ordering": ("-date_updated",)},
        ),
    ]
