# Generated by Django 2.2.16 on 2021-04-01 00:22

from django.db import migrations, models
import django.db.models.deletion
from world.crafting.migration_helpers import get_material_mapping


def convert_sales(apps, schema_editor):
    """Populates new fk in BrokeredSale"""
    BrokeredSale = apps.get_model("petitions", "BrokeredSale")
    mapping = get_material_mapping(apps)
    for sale in BrokeredSale.objects.filter(crafting_material_type__isnull=False):
        new_mat = mapping[sale.crafting_material_type_id]
        sale.new_type = new_mat
        sale.save()


class Migration(migrations.Migration):

    dependencies = [
        ("petitions", "0005_auto_20190908_0924"),
        ("crafting", "0002_migrate_attributes_to_crafting"),
    ]

    operations = [
        migrations.AddField(
            model_name="brokeredsale",
            name="new_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="crafting.CraftingMaterialType",
            ),
        ),
        migrations.RunPython(convert_sales, migrations.RunPython.noop, elidable=True),
        migrations.RemoveField(
            model_name="brokeredsale",
            name="crafting_material_type",
        ),
        migrations.RenameField(
            model_name="brokeredsale",
            old_name="new_type",
            new_name="crafting_material_type",
        ),
    ]
