# Generated by Django 2.2.24 on 2022-07-15 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("prayer", "0002_religion"),
        ("character_extensions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="charactersheet",
            name="religion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="character_sheets",
                to="prayer.Religion",
            ),
        ),
    ]
