# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-28 03:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0005_auto_20150403_2339'),
        ('helpdesk', '0006_ticket_submitting_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='submitting_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='objects.ObjectDB', verbose_name='Room where this was submitted'),
        ),
    ]
