# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-05-21 17:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('helpdesk', '0008_auto_20170116_1712'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='created',
            new_name='db_date_created',
        ),
        migrations.AddField(
            model_name='ticket',
            name='participants',
            field=models.ManyToManyField(blank=True, null=True, related_name='assisted_storyactions', to=settings.AUTH_USER_MODEL),
        ),
    ]
