# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-01 03:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0033_goal_goalupdate'),
        ('helpdesk', '0012_auto_20181116_0459'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='goal_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='character.GoalUpdate'),
        ),
    ]
