# Generated by Django 2.2.24 on 2021-09-27 15:07

from django.db import migrations, models


def add_attack_check(apps, schema_editor):
    """Add attack check to the game"""
    StatCombination = apps.get_model("stat_checks", "StatCombination")
    StatCheck = apps.get_model("stat_checks", "StatCheck")
    dice_system = StatCombination.objects.create(dynamic_system=1)
    StatCheck.objects.create(
        name="attack check",
        dice_system=dice_system,
        description="How a character makes an attack check. The system "
        "used depends on the attack, generally derived from their weapon "
        "for player characters.",
    )


class Migration(migrations.Migration):

    dependencies = [
        ("stat_checks", "0004_auto_20210906_1457"),
    ]

    operations = [
        migrations.AddField(
            model_name="statcombination",
            name="dynamic_system",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "Not a dynamic system"), (1, "Character Attack System")],
                default=0,
            ),
        ),
        migrations.RunPython(
            add_attack_check, migrations.RunPython.noop, elidable=False
        ),
    ]
