# Generated by Django 2.2.24 on 2021-10-03 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stat_checks", "0005_statcombination_dynamic_system"),
    ]

    operations = [
        migrations.AddField(
            model_name="statcheck",
            name="category",
            field=models.CharField(blank=True, default="general", max_length=50),
        ),
    ]
