# Generated by Django 2.2.16 on 2021-04-01 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("exploration", "0002_fix_exploration_dependencies"),
        ("crafting", "0002_migrate_attributes_to_crafting"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monstercraftingdrop",
            name="material",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="monsters",
                to="crafting.CraftingMaterialType",
            ),
        ),
        migrations.AlterField(
            model_name="shardhavenpuzzlecraftingmaterial",
            name="material",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="crafting.CraftingMaterialType",
            ),
        ),
    ]
