# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-05 18:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("exploration", "0005_auto_20181105_1829"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shardhavenlayoutsquare",
            name="exit_east",
        ),
        migrations.RemoveField(
            model_name="shardhavenlayoutsquare",
            name="exit_north",
        ),
        migrations.RemoveField(
            model_name="shardhavenlayoutsquare",
            name="exit_south",
        ),
        migrations.RemoveField(
            model_name="shardhavenlayoutsquare",
            name="exit_west",
        ),
        migrations.AddField(
            model_name="shardhavenlayoutexit",
            name="room_east",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exit_west",
                to="exploration.ShardhavenLayoutSquare",
            ),
        ),
        migrations.AddField(
            model_name="shardhavenlayoutexit",
            name="room_north",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exit_south",
                to="exploration.ShardhavenLayoutSquare",
            ),
        ),
        migrations.AddField(
            model_name="shardhavenlayoutexit",
            name="room_south",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exit_north",
                to="exploration.ShardhavenLayoutSquare",
            ),
        ),
        migrations.AddField(
            model_name="shardhavenlayoutexit",
            name="room_west",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exit_east",
                to="exploration.ShardhavenLayoutSquare",
            ),
        ),
    ]
