# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-08 23:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("exploration", "0010_shardhavenlayoutsquare_room"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShardhavenMoodFragment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                (
                    "shardhaven_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="exploration.ShardhavenType",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
