# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-11 20:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("exploration", "0012_auto_20181111_2015"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shardhavenobstacle",
            name="rolls",
        ),
        migrations.AddField(
            model_name="shardhavenobstacleroll",
            name="obstacle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rolls",
                to="exploration.ShardhavenObstacle",
            ),
        ),
    ]
