# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-13 22:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("magic", "0002_auto_20181113_2246"),
        ("objects", "0009_remove_objectdb_db_player"),
        ("exploration", "0015_auto_20181112_2259"),
    ]

    operations = [
        migrations.CreateModel(
            name="Monster",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                ("plural_name", models.CharField(blank=True, max_length=40, null=True)),
                ("description", models.TextField()),
                ("spawn_message", models.TextField(blank=True, null=True)),
                ("difficulty", models.PositiveSmallIntegerField(default=5)),
                (
                    "npc_type",
                    models.PositiveSmallIntegerField(
                        choices=[(0, b"Mooks"), (1, b"Boss")], default=0
                    ),
                ),
                (
                    "npc_template",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, b"Guard"),
                            (1, b"Thug"),
                            (2, b"Spy"),
                            (4, b"Champion"),
                            (3, b"Assistant"),
                            (5, b"Animal"),
                            (6, b"Small Animal"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "minimum_quantity",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text=b"Minimum number of Mooks to spawn (mooks only)",
                    ),
                ),
                (
                    "maximum_quantity",
                    models.PositiveSmallIntegerField(
                        default=10,
                        help_text=b"Maximum number of Mooks to spawn (mooks only)",
                    ),
                ),
                (
                    "boss_rating",
                    models.PositiveSmallIntegerField(
                        default=1, help_text=b"Boss rating (boss only)"
                    ),
                ),
                (
                    "threat_rating",
                    models.PositiveSmallIntegerField(
                        default=1, help_text=b"The threat rating for this monster"
                    ),
                ),
                (
                    "mirror",
                    models.BooleanField(
                        default=False,
                        help_text=b"Should this monster mirror the stats of a player in the party?",
                    ),
                ),
                (
                    "weight_no_drop",
                    models.PositiveSmallIntegerField(
                        default=10,
                        help_text=b"The weight value to use for No Drop in drop calculations.",
                    ),
                ),
                (
                    "habitats",
                    models.ManyToManyField(
                        related_name="denizens", to="exploration.ShardhavenType"
                    ),
                ),
                (
                    "instances",
                    models.ManyToManyField(
                        related_name="_monster_instances_+", to="objects.ObjectDB"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MonsterDrops",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weight", models.PositiveSmallIntegerField(default=10)),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monsters",
                        to="magic.AlchemicalMaterial",
                    ),
                ),
                (
                    "monster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drops",
                        to="exploration.Monster",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="shardhaven",
            name="difficulty_rating",
            field=models.PositiveSmallIntegerField(default=4),
        ),
    ]
