# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-13 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exploration", "0016_auto_20181113_2246"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monster",
            name="instances",
            field=models.ManyToManyField(
                related_name="monsters", to="objects.ObjectDB"
            ),
        ),
    ]
