# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-14 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exploration', '0018_auto_20181114_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedLootFragment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fragment_type', models.PositiveSmallIntegerField(choices=[(0, 'Adjective'), (1, 'Bauble Material'), (2, 'Type of Item'), (3, 'Name fragment (first)'), (4, 'Name fragment (second)'), (5, 'Name fragment (prefix)'), (6, 'Small Weapon Type'), (7, 'Medium Weapon Type'), (8, 'Huge Weapon Type')], default=0)),
                ('text', models.CharField(max_length=25)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
