# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-14 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exploration", "0022_auto_20181114_2224"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generatedlootfragment",
            name="text",
            field=models.CharField(max_length=45),
        ),
    ]
