# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-15 01:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exploration", "0023_auto_20181114_2225"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="generatedlootfragment",
            unique_together=set([("fragment_type", "text")]),
        ),
    ]
