# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-15 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exploration", "0025_auto_20181115_2011"),
    ]

    operations = [
        migrations.AddField(
            model_name="monster",
            name="weight_trinket",
            field=models.PositiveSmallIntegerField(
                default=1, help_text="The weight value to use for Trinkets"
            ),
        ),
        migrations.AddField(
            model_name="monster",
            name="weight_weapon",
            field=models.PositiveSmallIntegerField(
                default=1, help_text="The weight value to use for Weapons"
            ),
        ),
    ]
