# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-16 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exploration', '0029_shardhavenobstacle_clue_success'),
    ]

    operations = [
        migrations.AddField(
            model_name='shardhavenobstacleroll',
            name='pass_instantly',
            field=models.BooleanField(default=False, verbose_name=b'Should a player immediately pass through the exit on success?'),
        ),
    ]
