# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-16 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exploration", "0030_shardhavenobstacleroll_pass_instantly"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monster",
            name="weight_trinket",
            field=models.PositiveSmallIntegerField(
                default=0, help_text=b"The weight value to use for Trinkets"
            ),
        ),
        migrations.AlterField(
            model_name="monster",
            name="weight_weapon",
            field=models.PositiveSmallIntegerField(
                default=0, help_text=b"The weight value to use for Weapons"
            ),
        ),
    ]
