# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-17 01:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exploration", "0031_auto_20181116_2351"),
    ]

    operations = [
        migrations.AddField(
            model_name="shardhavenlayoutexit",
            name="override",
            field=models.BooleanField(default=False),
        ),
    ]
