# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-18 01:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exploration", "0034_monster_weight_spawn"),
    ]

    operations = [
        migrations.AddField(
            model_name="shardhaven",
            name="weight_boss_monster",
            field=models.PositiveSmallIntegerField(
                default=5, verbose_name=b"Boss Spawn Weight"
            ),
        ),
        migrations.AddField(
            model_name="shardhaven",
            name="weight_mook_monster",
            field=models.PositiveSmallIntegerField(
                default=5, verbose_name=b"Mook Spawn Weight"
            ),
        ),
        migrations.AddField(
            model_name="shardhaven",
            name="weight_no_monster",
            field=models.PositiveSmallIntegerField(
                default=40, verbose_name=b"No Spawn Weight"
            ),
        ),
        migrations.AddField(
            model_name="shardhaven",
            name="weight_no_treasure",
            field=models.PositiveSmallIntegerField(
                default=50, verbose_name=b"No Treasure Weight"
            ),
        ),
        migrations.AddField(
            model_name="shardhaven",
            name="weight_trinket",
            field=models.PositiveSmallIntegerField(
                default=5, verbose_name=b"Trinket Weight"
            ),
        ),
        migrations.AddField(
            model_name="shardhaven",
            name="weight_weapon",
            field=models.PositiveSmallIntegerField(
                default=1, verbose_name=b"Weapon Weight"
            ),
        ),
    ]
