# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-18 01:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exploration", "0035_auto_20181118_0103"),
    ]

    operations = [
        migrations.AddField(
            model_name="shardhaven",
            name="weight_no_monster_backtrack",
            field=models.PositiveSmallIntegerField(
                default=100, verbose_name=b"No Spawn Weight on Backtrack"
            ),
        ),
    ]
