# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-22 02:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exploration", "0040_auto_20181120_2016"),
    ]

    operations = [
        migrations.AddField(
            model_name="shardhavenobstacle",
            name="obstacle_class",
            field=models.PositiveSmallIntegerField(
                choices=[(0, b"Pass an Exit"), (1, b"Obtain a Treasure")], default=0
            ),
        ),
    ]
