# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-22 13:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dominion', '0035_auto_20180831_0922'),
        ('magic', '0004_alchemicalmaterial_plural_name'),
        ('objects', '0009_remove_objectdb_db_player'),
        ('exploration', '0041_shardhavenobstacle_obstacle_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShardhavenPuzzle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_trinket', models.SmallIntegerField(default=0, help_text=b'A weight chance that this puzzle will drop a trinket.')),
                ('weight_weapon', models.SmallIntegerField(default=0, help_text=b'A weight chance that this puzzle will drop a weapon.')),
                ('obstacle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puzzles', to='exploration.ShardhavenObstacle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShardhavenPuzzleCraftingMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.SmallIntegerField(default=10, help_text=b'A weight chance that this puzzle will drop this material.')),
                ('minimum_quantity', models.PositiveSmallIntegerField(default=1)),
                ('maximum_quantity', models.PositiveSmallIntegerField(default=1)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dominion.CraftingMaterialType')),
                ('puzzle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crafting_materials', to='exploration.ShardhavenPuzzle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShardhavenPuzzleMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.SmallIntegerField(default=10, help_text=b'A weight chance that this puzzle will drop this material.')),
                ('minimum_quantity', models.PositiveSmallIntegerField(default=1)),
                ('maximum_quantity', models.PositiveSmallIntegerField(default=1)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magic.AlchemicalMaterial')),
                ('puzzle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alchemical_materials', to='exploration.ShardhavenPuzzle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShardhavenPuzzleObjectLoot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.SmallIntegerField(default=10, help_text=b'A weight chance that this puzzle will drop this object.')),
                ('duplicate', models.BooleanField(default=False)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.ObjectDB')),
                ('puzzle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crafting_materials', to='exploration.ShardhavenPuzzle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='monsterdrops',
            name='max_quantity',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='monsterdrops',
            name='min_quantity',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
