# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-22 22:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('exploration', '0044_auto_20181122_2135'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MonsterDrops',
            new_name='MonsterAlchemicalDrop',
        ),
        migrations.RenameModel(
            old_name='MonsterCraftingDrops',
            new_name='MonsterCraftingDrop',
        ),
    ]
