# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-22 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exploration', '0045_auto_20181122_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='shardhavenpuzzle',
            name='name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
