# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-23 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exploration', '0049_auto_20181123_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='shardhavenobstacle',
            name='short_desc',
            field=models.CharField(blank=True, help_text=b"A short description of this obstacle, like 'labyrinth of mirrors'.", max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='shardhavenpuzzle',
            name='num_drops',
            field=models.PositiveSmallIntegerField(default=1, help_text=b'How many treasures should this puzzle drop?'),
        ),
    ]
