# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-23 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exploration', '0051_auto_20181123_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='shardhavenpuzzleobjectloot',
            name='guaranteed',
            field=models.BooleanField(default=False, help_text=b'Is this object a guaranteed drop?'),
        ),
        migrations.AlterField(
            model_name='shardhavenpuzzleobjectloot',
            name='duplicate',
            field=models.BooleanField(default=False, help_text=b'Do we create a duplicate copy of this object to drop?'),
        ),
    ]
