# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-28 15:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crafting', '0001_initial'),
        ('exploration', '0053_auto_20181202_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monstercraftingdrop',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monsters', to='crafting.CraftingMaterialType'),
        ),
        migrations.AlterField(
            model_name='shardhavenpuzzlecraftingmaterial',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crafting.CraftingMaterialType'),
        ),
    ]
