# Generated by Django 2.2.28 on 2023-07-08 15:16
from collections import defaultdict

from django.db import migrations, models
import django.db.models.deletion

from utils.progress_bar import ProgressBar


def convert_seasonal_descs(apps, schema_editor):
    Attribute = apps.get_model("typeclasses", "Attribute")
    RoomDescriptions = apps.get_model("room_extensions", "RoomDescriptions")
    descriptions_dict = defaultdict(RoomDescriptions)
    for season in ("spring", "summer", "autumn", "winter"):
        qs = Attribute.objects.filter(db_key=f"{season}_desc")
        num = 0
        total = len(qs)
        if total:
            print(f"\nConverting {season}_desc: {total} records.")
        for attr in qs:
            try:
                num += 1
                progress = num / total
                print(ProgressBar(progress, "Progress: "), end="\r", flush=True)
                objdb = attr.objectdb_set.all()[0]
                if not attr.db_value or not isinstance(attr.db_value, str):
                    attr.delete()
                    continue
                room_desc = descriptions_dict[objdb.pk]
                room_desc.room = objdb
                setattr(room_desc, f"{season}_description", attr.db_value)
                room_desc.save()
                attr.delete()
            except IndexError:
                pass
        if total:
            print("\n")


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("objects", "0011_auto_20191025_0831"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoomDescriptions",
            fields=[
                ("spring_description", models.TextField(blank=True)),
                ("summer_description", models.TextField(blank=True)),
                ("autumn_description", models.TextField(blank=True)),
                ("winter_description", models.TextField(blank=True)),
                ("room_mood", models.TextField(blank=True)),
                ("mood_set_at", models.DateTimeField(blank=True, null=True)),
                (
                    "room",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="room_descriptions",
                        serialize=False,
                        to="objects.ObjectDB",
                    ),
                ),
                (
                    "mood_set_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="set_moods",
                        to="objects.ObjectDB",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "verbose_name_plural": "Room Extra Descriptions",
            },
        ),
        migrations.RunPython(
            convert_seasonal_descs, migrations.RunPython.noop, elidable=True
        ),
    ]
