# Generated by Django 2.2.9 on 2020-05-30 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('character', '0035_auto_20191228_1417'),
        ('dominion', '0047_actionrequirement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ic_desc', models.TextField(blank=True)),
                ('gm_note', models.TextField(blank=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('db_date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuestStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quest_completed', models.DateTimeField(blank=True, help_text='Generated when all steps are marked complete.', null=True, verbose_name='Completed On')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='dominion.AssetOwner', verbose_name='Character/Org')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='quests.Quest')),
            ],
            options={
                'verbose_name_plural': 'Quest Statuses',
            },
        ),
        migrations.CreateModel(
            name='QuestStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ic_desc', models.TextField(blank=True)),
                ('gm_note', models.TextField(blank=True)),
                ('name', models.CharField(max_length=255)),
                ('step_number', models.PositiveSmallIntegerField(default=0)),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quest_steps', to='quests.Quest')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuestStepEffort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveSmallIntegerField(default=0)),
                ('step_completed', models.DateTimeField(blank=True, help_text='Mark this date to complete this step of the quest.', null=True, verbose_name='Marked Complete On')),
                ('action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='used_in_efforts', to='dominion.PlotAction')),
                ('char_clue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='used_in_efforts', to='character.ClueDiscovery')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='used_in_efforts', to='dominion.RPEvent')),
                ('flashback', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='used_in_efforts', to='character.Flashback')),
                ('org_clue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='used_in_efforts', to='dominion.ClueForOrg')),
                ('quest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='used_in_efforts', to='quests.QuestStatus')),
                ('revelation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='used_in_efforts', to='character.RevelationDiscovery')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='efforts', to='quests.QuestStatus')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='efforts', to='quests.QuestStep')),
            ],
        ),
        migrations.AddField(
            model_name='quest',
            name='entities',
            field=models.ManyToManyField(related_name='quests', through='quests.QuestStatus', to='dominion.AssetOwner'),
        ),
    ]
