# Generated by Django 2.2.24 on 2021-10-30 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dominion", "0004_auto_20211030_1419"),
        ("character", "0003_auto_20210704_1214"),
    ]

    operations = [
        migrations.AddField(
            model_name="playeraccount",
            name="episodes",
            field=models.ManyToManyField(
                related_name="accounts",
                through="dominion.ActionPerEpisode",
                to="character.Episode",
            ),
        ),
    ]
