# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-17 06:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0003_theory"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="theory",
            options={"verbose_name_plural": "Theories"},
        ),
    ]
