# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-28 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0005_auto_20170122_0008"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accounthistory",
            name="end_date",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="accounthistory",
            name="start_date",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="chapter",
            name="name",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="clue",
            name="characters",
            field=models.ManyToManyField(
                blank=True,
                db_index=True,
                through="character.ClueDiscovery",
                to="character.RosterEntry",
            ),
        ),
        migrations.AlterField(
            model_name="clue",
            name="name",
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="clue",
            name="rating",
            field=models.PositiveSmallIntegerField(
                blank=0,
                db_index=True,
                default=0,
                help_text=b"Value required to get this clue",
            ),
        ),
        migrations.AlterField(
            model_name="clue",
            name="revelations",
            field=models.ManyToManyField(
                db_index=True,
                through="character.ClueForRevelation",
                to="character.Revelation",
            ),
        ),
        migrations.AlterField(
            model_name="cluediscovery",
            name="roll",
            field=models.PositiveSmallIntegerField(blank=0, db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name="episode",
            name="date",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="episode",
            name="name",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="investigation",
            name="active",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text=b"Whether this is the investigation for the week. Only one allowed",
            ),
        ),
        migrations.AlterField(
            model_name="investigation",
            name="ongoing",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text=b"Whether this investigation is finished or not",
            ),
        ),
        migrations.AlterField(
            model_name="mystery",
            name="characters",
            field=models.ManyToManyField(
                blank=True,
                db_index=True,
                through="character.MysteryDiscovery",
                to="character.RosterEntry",
            ),
        ),
        migrations.AlterField(
            model_name="mystery",
            name="name",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="revelation",
            name="characters",
            field=models.ManyToManyField(
                blank=True,
                db_index=True,
                through="character.RevelationDiscovery",
                to="character.RosterEntry",
            ),
        ),
        migrations.AlterField(
            model_name="revelation",
            name="name",
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="roster",
            name="name",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="story",
            name="name",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
    ]
