# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-05-19 16:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0011_auto_20170516_0458"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="firstcontact",
            options={"verbose_name_plural": "First Impressions"},
        ),
    ]
