# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-06-05 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0013_auto_20170605_1756"),
    ]

    operations = [
        migrations.AddField(
            model_name="firstcontact",
            name="viewable_by_all",
            field=models.BooleanField(default=False),
        ),
    ]
