# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-06-05 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0014_firstcontact_viewable_by_all'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firstcontact',
            name='viewable_by_all',
        ),
        migrations.AddField(
            model_name='firstcontact',
            name='receiver_share',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='firstcontact',
            name='writer_share',
            field=models.BooleanField(default=False),
        ),
    ]
