# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-25 05:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0016_auto_20170925_0500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theory',
            name='known_by',
        ),
    ]
