# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-29 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0018_auto_20170925_0515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigation',
            name='roll',
            field=models.SmallIntegerField(blank=True, default=-9999, help_text='Current dice roll'),
        ),
        migrations.AlterField(
            model_name='investigation',
            name='topic',
            field=models.CharField(blank=True, help_text='Keywords or tldr or title', max_length=255),
        ),
    ]
