# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-26 02:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0021_flashback_flashbackpost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flashbackpost",
            name="actions",
            field=models.TextField(
                blank=True,
                verbose_name=b"The body of the post for your character's actions",
            ),
        ),
    ]
