# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-18 00:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0022_auto_20171226_0208'),
    ]

    operations = [
        migrations.AddField(
            model_name='clue',
            name='gm_notes',
            field=models.TextField(blank=True, help_text='Notes visible only to staff/GMs about this clue', verbose_name='GM Notes'),
        ),
    ]
