# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-10 19:31
from __future__ import unicode_literals

from django.db import migrations, models


def delete_duplicates(apps, schema_editor):
    from collections import defaultdict
    fields_to_object = defaultdict(list)
    InvestigationAssistant = apps.get_model('character', "InvestigationAssistant")
    for obj in InvestigationAssistant.objects.all():
        fields_to_object[(obj.char_id, obj.investigation_id)].append(obj)
    matches = [item for item in fields_to_object.values() if len(item) > 1]
    ids_to_delete = []
    for match_list in matches:
        ids = [ob.id for ob in match_list[1:]]
        ids_to_delete.extend(ids)
    InvestigationAssistant.objects.filter(id__in=ids_to_delete).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0009_remove_objectdb_db_player'),
        ('character', '0023_clue_gm_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigationassistant',
            name='currently_helping',
            field=models.BooleanField(default=False, help_text=b"Whether they're currently helping out"),
        ),
        migrations.RunPython(delete_duplicates),
        migrations.AlterUniqueTogether(
            name='investigationassistant',
            unique_together=set([('char', 'investigation')]),
        ),
    ]
