# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-08 19:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def add_involvements(apps, schema_editor):
    """Change owner / allowed fields to be options on a FlashbackInvolvement."""
    # TODO: Define classes then loop stuff. FlashbackPostPermissions here too?
    Flashback = apps.get_model('character', 'Flashback')
    FlashbackInvolvement = apps.get_model('character', 'FlashbackInvolvement')
    for flashback in Flashback.objects.all():
        involved = []
        # TODO: find the various details of involvement
        pass
    FlashbackInvolvement.objects.bulk_create(involved)
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0033_goal_goalupdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashbackInvolvement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(blank=True, choices=[(0, b'Retired'), (1, b'Contributor'), (2, b'Owner')], default=1)),
                ('roll', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='FlashbackPostPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='flashback',
            name='concluded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='flashbackpost',
            name='roll',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='flashbackpost',
            name='poster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flashback_posts', to='character.RosterEntry'),
        ),
        migrations.AddField(
            model_name='flashbackpostpermission',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashback_post_permissions', to='character.FlashbackPost'),
        ),
        migrations.AddField(
            model_name='flashbackpostpermission',
            name='reader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashback_post_permissions', to='character.RosterEntry'),
        ),
        migrations.AddField(
            model_name='flashbackinvolvement',
            name='flashback',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashback_involvements', to='character.Flashback'),
        ),
        migrations.AddField(
            model_name='flashbackinvolvement',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashback_involvements', to='character.RosterEntry'),
        ),
        migrations.AddField(
            model_name='flashback',
            name='participants',
            field=models.ManyToManyField(related_name='flashbacks', through='character.FlashbackInvolvement', to='character.RosterEntry'),
        ),
        migrations.AddField(
            model_name='flashbackpost',
            name='readable_by',
            field=models.ManyToManyField(blank=True, related_name='readable_flashback_posts', through='character.FlashbackPostPermission', to='character.RosterEntry'),
        ),
        migrations.AlterUniqueTogether(
            name='flashbackpostpermission',
            unique_together=set([('post', 'reader')]),
        ),
        migrations.AlterUniqueTogether(
            name='flashbackinvolvement',
            unique_together=set([('flashback', 'participant')]),
        ),
        # TODO: migrations.RunPython(stuff)
        migrations.RemoveField(
            model_name='flashback',
            name='allowed',
        ),
        migrations.RemoveField(
            model_name='flashback',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='flashbackpost',
            name='read_by',
        ),
    ]
