# Generated by Django 2.2.9 on 2019-12-28 14:17

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0034_auto_20190508_1944"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clue",
            name="allow_exploration",
            field=models.BooleanField(
                default=False, help_text="Can be gained through exploration rolls"
            ),
        ),
        migrations.AlterField(
            model_name="clue",
            name="allow_investigation",
            field=models.BooleanField(
                default=False, help_text="Can be gained through investigation rolls"
            ),
        ),
        migrations.AlterField(
            model_name="clue",
            name="allow_trauma",
            field=models.BooleanField(
                default=False, help_text="Can be gained through combat rolls"
            ),
        ),
        migrations.AlterField(
            model_name="clue",
            name="desc",
            field=models.TextField(
                blank=True,
                help_text="Description of the clue given to the player",
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="clue",
            name="rating",
            field=models.PositiveSmallIntegerField(
                blank=0,
                db_index=True,
                default=0,
                help_text="Value required to get this clue",
            ),
        ),
        migrations.AlterField(
            model_name="clue",
            name="red_herring",
            field=models.BooleanField(
                default=False, help_text="Whether this revelation is totally fake"
            ),
        ),
        migrations.AlterField(
            model_name="clue",
            name="tangible_object",
            field=models.ForeignKey(
                blank=True,
                help_text="An in-game object that this Clue is a secret or backstory for",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clues",
                to="objects.ObjectDB",
            ),
        ),
        migrations.AlterField(
            model_name="cluediscovery",
            name="message",
            field=models.TextField(
                blank=True,
                help_text="Message for the player's records about how they discovered this.",
            ),
        ),
        migrations.AlterField(
            model_name="clueforrevelation",
            name="required_for_revelation",
            field=models.BooleanField(
                default=True,
                help_text="Whether this must be discovered for the revelation to finish",
            ),
        ),
        migrations.AlterField(
            model_name="clueforrevelation",
            name="tier",
            field=models.PositiveSmallIntegerField(
                blank=0,
                default=0,
                help_text="How high in the hierarchy of discoveries this clue is, lower number discovered first",
            ),
        ),
        migrations.AlterField(
            model_name="clueplotinvolvement",
            name="access",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "Neutral"), (1, "Hooked"), (2, "Granted")], default=0
            ),
        ),
        migrations.AlterField(
            model_name="flashbackpost",
            name="actions",
            field=models.TextField(
                blank=True,
                verbose_name="The body of the post for your character's actions",
            ),
        ),
        migrations.AlterField(
            model_name="goal",
            name="description",
            field=models.TextField(verbose_name="Detailed description of the goal"),
        ),
        migrations.AlterField(
            model_name="goal",
            name="gm_notes",
            field=models.TextField(
                blank=True, verbose_name="Notes by staff, not visible to the player"
            ),
        ),
        migrations.AlterField(
            model_name="goal",
            name="ooc_notes",
            field=models.TextField(
                blank=True, verbose_name="Any OOC notes by the player about the goal"
            ),
        ),
        migrations.AlterField(
            model_name="goal",
            name="scope",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Heartbreakingly Modest"),
                    (1, "Modest"),
                    (2, "Reasonable"),
                    (3, "Ambitious"),
                    (4, "Venomously Ambitious"),
                    (5, "Megalomanic"),
                ],
                default=2,
            ),
        ),
        migrations.AlterField(
            model_name="goal",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Succeeded"),
                    (1, "Failed"),
                    (2, "Abandoned"),
                    (3, "Dormant"),
                    (4, "Active"),
                ],
                default=4,
            ),
        ),
        migrations.AlterField(
            model_name="goal",
            name="summary",
            field=models.CharField(max_length=80, verbose_name="Summary of the goal"),
        ),
        migrations.AlterField(
            model_name="goalupdate",
            name="gm_notes",
            field=models.TextField(
                blank=True, verbose_name="OOC notes for staff about consequences"
            ),
        ),
        migrations.AlterField(
            model_name="goalupdate",
            name="result",
            field=models.TextField(
                blank=True, verbose_name="IC description of the outcome for the player"
            ),
        ),
        migrations.AlterField(
            model_name="investigation",
            name="actions",
            field=models.TextField(
                blank=True,
                help_text="The writeup the player submits of their actions, used for GMing.",
            ),
        ),
        migrations.AlterField(
            model_name="investigation",
            name="active",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Whether this is the investigation for the week. Only one allowed",
            ),
        ),
        migrations.AlterField(
            model_name="investigation",
            name="automate_result",
            field=models.BooleanField(
                default=True,
                help_text="Whether to generate a result during weekly maintenance. Set false if GM'd",
            ),
        ),
        migrations.AlterField(
            model_name="investigation",
            name="completion_value",
            field=models.IntegerField(
                default=300, help_text="Total progress needed to make a discovery."
            ),
        ),
        migrations.AlterField(
            model_name="investigation",
            name="economic",
            field=models.PositiveSmallIntegerField(
                blank=0,
                default=0,
                help_text="Additional economic resources added by the player",
            ),
        ),
        migrations.AlterField(
            model_name="investigation",
            name="military",
            field=models.PositiveSmallIntegerField(
                blank=0,
                default=0,
                help_text="Additional military resources added by the player",
            ),
        ),
        migrations.AlterField(
            model_name="investigation",
            name="ongoing",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Whether this investigation is finished or not",
            ),
        ),
        migrations.AlterField(
            model_name="investigation",
            name="progress",
            field=models.IntegerField(
                default=0, help_text="Progress made towards a discovery."
            ),
        ),
        migrations.AlterField(
            model_name="investigation",
            name="results",
            field=models.TextField(
                blank=True,
                default="You didn't find anything.",
                help_text="The text to send the player, either set by GM or generated automatically by script if automate_result is set.",
            ),
        ),
        migrations.AlterField(
            model_name="investigation",
            name="silver",
            field=models.PositiveSmallIntegerField(
                blank=0, default=0, help_text="Additional silver added by the player"
            ),
        ),
        migrations.AlterField(
            model_name="investigation",
            name="skill_used",
            field=models.CharField(
                blank=True,
                default="investigation",
                help_text="The skill the player chose to use",
                max_length=80,
            ),
        ),
        migrations.AlterField(
            model_name="investigation",
            name="social",
            field=models.PositiveSmallIntegerField(
                blank=0,
                default=0,
                help_text="Additional social resources added by the player",
            ),
        ),
        migrations.AlterField(
            model_name="investigation",
            name="stat_used",
            field=models.CharField(
                blank=True,
                default="perception",
                help_text="The stat the player chose to use",
                max_length=80,
            ),
        ),
        migrations.AlterField(
            model_name="investigationassistant",
            name="currently_helping",
            field=models.BooleanField(
                default=False, help_text="Whether they're currently helping out"
            ),
        ),
        migrations.AlterField(
            model_name="mystery",
            name="category",
            field=models.CharField(
                blank=True,
                help_text="Type of mystery this is - ability-related, metaplot, etc",
                max_length=80,
            ),
        ),
        migrations.AlterField(
            model_name="photo",
            name="alt_text",
            field=models.CharField(
                blank=True,
                max_length=200,
                verbose_name="Optional 'alt' text when mousing over your image",
            ),
        ),
        migrations.AlterField(
            model_name="photo",
            name="image",
            field=cloudinary.models.CloudinaryField(
                max_length=255, verbose_name="image"
            ),
        ),
        migrations.AlterField(
            model_name="photo",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="a Character owner of this image, if any.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="objects.ObjectDB",
                verbose_name="owner",
            ),
        ),
        migrations.AlterField(
            model_name="photo",
            name="title",
            field=models.CharField(
                blank=True,
                max_length=200,
                verbose_name="Name or description of the picture (optional)",
            ),
        ),
        migrations.AlterField(
            model_name="revelation",
            name="desc",
            field=models.TextField(
                blank=True,
                help_text="Description of the revelation given to the player",
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="revelation",
            name="gm_notes",
            field=models.TextField(blank=True, help_text="OOC Notes about this topic"),
        ),
        migrations.AlterField(
            model_name="revelation",
            name="red_herring",
            field=models.BooleanField(
                default=False, help_text="Whether this revelation is totally fake"
            ),
        ),
        migrations.AlterField(
            model_name="revelation",
            name="required_clue_value",
            field=models.PositiveSmallIntegerField(
                blank=0, default=0, help_text="The total value of clues to trigger this"
            ),
        ),
        migrations.AlterField(
            model_name="revelationdiscovery",
            name="discovery_method",
            field=models.CharField(
                help_text="How this was discovered - exploration, trauma, etc",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="revelationdiscovery",
            name="message",
            field=models.TextField(
                blank=True,
                help_text="Message for the player's records about how they discovered this.",
            ),
        ),
        migrations.AlterField(
            model_name="roster",
            name="lock_storage",
            field=models.TextField(
                blank=True, help_text="defined in setup_utils", verbose_name="locks"
            ),
        ),
        migrations.AlterField(
            model_name="rosterentry",
            name="lock_storage",
            field=models.TextField(
                blank=True, help_text="defined in setup_utils", verbose_name="locks"
            ),
        ),
        migrations.AlterField(
            model_name="rpscene",
            name="lock_storage",
            field=models.TextField(
                blank=True, help_text="defined in setup_utils", verbose_name="locks"
            ),
        ),
        migrations.AlterField(
            model_name="rpscene",
            name="log",
            field=models.TextField(verbose_name="Text log of the scene"),
        ),
        migrations.AlterField(
            model_name="rpscene",
            name="synopsis",
            field=models.TextField(
                verbose_name="Description of the scene written by player"
            ),
        ),
        migrations.AlterField(
            model_name="rpscene",
            name="title",
            field=models.CharField(max_length=80, verbose_name="title of the scene"),
        ),
    ]
