# Generated by Django 2.2.20 on 2021-06-06 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("object_extensions", "0002_displaynames"),
    ]

    operations = [
        migrations.AddField(
            model_name="dimensions",
            name="is_locked",
            field=models.BooleanField(
                default=False,
                help_text="If this is a container or exit, whether it's locked.",
            ),
        ),
    ]
