# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-26 03:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("objects", "0009_remove_objectdb_db_player"),
        ("fashion", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FashionOutfit",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, unique=True)),
                ("db_date_created", models.DateTimeField(auto_now_add=True)),
                ("archived", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ModusOrnamenta",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slot", models.CharField(blank=True, max_length=80, null=True)),
                (
                    "fashion_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="objects.ObjectDB",
                    ),
                ),
                (
                    "fashion_outfit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fashion.FashionOutfit",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="fashionoutfit",
            name="fashion_items",
            field=models.ManyToManyField(
                blank=True, through="fashion.ModusOrnamenta", to="objects.ObjectDB"
            ),
        ),
        migrations.AddField(
            model_name="fashionoutfit",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fashion_outfits",
                to="dominion.PlayerOrNpc",
            ),
        ),
        migrations.AddField(
            model_name="fashionsnapshot",
            name="outfit",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fashion_snapshots",
                to="fashion.FashionOutfit",
            ),
        ),
    ]
