# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-12 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0009_remove_objectdb_db_player'),
        ('fashion', '0003_auto_20180827_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='fashionsnapshot',
            name='characters',
            field=models.ManyToManyField(related_name='_fashionsnapshot_characters_+', to='objects.ObjectDB'),
        ),
        migrations.AddField(
            model_name='fashionsnapshot',
            name='multiplier',
            field=models.FloatField(default=1.0),
        ),
    ]
