# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-12 21:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0004_auto_20181112_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fashionsnapshot',
            name='characters',
        ),
        migrations.RemoveField(
            model_name='fashionsnapshot',
            name='multiplier',
        ),
    ]
