# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-13 22:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='affinity',
            options={'verbose_name_plural': 'Affinities'},
        ),
    ]
