# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-22 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magic', '0003_alchemicalmaterial_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='alchemicalmaterial',
            name='plural_name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
