# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-11 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("magic", "0007_auto_20181202_2052"),
    ]

    operations = [
        migrations.AddField(
            model_name="practitionerspell",
            name="success_msg",
            field=models.TextField(
                blank=True, help_text=b"Custom message for our version of the spell"
            ),
        ),
        migrations.AlterField(
            model_name="effect",
            name="coded_effect",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, b"Sight"),
                    (1, b"Add Clue to Collection"),
                    (2, b"Add Successes to A Global Tally"),
                    (3, b"Add to Primum Value of Object"),
                    (4, b"Absorb Primum from an Object"),
                    (5, b"Attune to Object, Player, or Agent"),
                    (6, b"Boost a Stat"),
                    (7, b"Ward a Location"),
                    (9, b"Heal a Character"),
                    (10, b"Simply Emits Flavor Text"),
                    (11, b"Temporarily Reveal an Exploration Map"),
                    (12, b"Apply a Combat Condition"),
                    (13, b"Remove a Combat Condition"),
                    (14, b"Apply a Combat Effect"),
                    (15, b"Remove a Combat Effect"),
                    (16, b"Change the Weather"),
                    (17, b"Anima Ritual"),
                ],
                default=0,
            ),
        ),
    ]
